version: 2.1
orbs:
  docker: circleci/docker@2.0.1

jobs:

  build-and-deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - docker/check
      - docker/build:
          image: suculent/alpine-gulp
          dockerfile: Dockerfile
          tag: 'latest'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/alpine-gulp
          tag: 'latest'

workflows:

  build-and-deploy:

    jobs:

      - build-and-deploy:
          context:
            - thinx-docker-repo
          filters:
            branches:
              only:
                - master